/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Backgorund: typeof import('./src/components/Backgorund.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    ChapterDetail: typeof import('./src/components/ChapterDetail.vue')['default']
    ChapterList: typeof import('./src/components/ChapterList.vue')['default']
    DictList: typeof import('./src/components/DictList.vue')['default']
    DictModal: typeof import('./src/components/Toolbar/DictModal.vue')['default']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    FeedbackModal: typeof import('./src/components/Toolbar/FeedbackModal.vue')['default']
    Fireworks: typeof import('./src/components/Fireworks.vue')['default']
    Footer: typeof import('./src/components/Practice/Footer.vue')['default']
    IconWrapper: typeof import('./src/components/IconWrapper.vue')['default']
    Modal: typeof import('./src/components/Modal/Modal.vue')['default']
    PopConfirm: typeof import('./src/components/PopConfirm.vue')['default']
    Practice: typeof import('./src/components/Practice/Practice.vue')['default']
    Ring: typeof import('./src/components/Ring.vue')['default']
    SettingModal: typeof import('./src/components/Toolbar/SettingModal.vue')['default']
    Side: typeof import('./src/components/Side.vue')['default']
    Statistics: typeof import('./src/components/Modal/Statistics.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar/Toolbar.vue')['default']
    Tooltip: typeof import('./src/components/Tooltip.vue')['default']
    TypeArticle: typeof import('./src/components/Practice/TypeArticle.vue')['default']
    TypeWord: typeof import('./src/components/Practice/TypeWord.vue')['default']
    WordList: typeof import('./src/components/WordList.vue')['default']
  }
}
