import {DictResource, DictType} from "@/types.ts";

// 国际考试
const internationalExam: DictResource[] = [
  {
    id: 'BEC_2',
    name: '商务英语词汇',
    description: '商务英语词汇',
    url: 'BEC_2.json',
    length: 2753,
    category: '国际考试',
    tags: ['所有', 'BEC'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word,
  },
  {
    id: 'BEC_3',
    name: '新东方 BEC 词汇',
    description: '新东方 BEC 词汇',
    url: 'BEC_3.json',
    length: 2825,
    category: '国际考试',
    tags: ['所有', 'BEC', '新东方'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word,
  },
  {
    id: 'TOEFL_2',
    name: 'TOEFL 词汇',
    description: 'TOEFL 词汇',
    url: 'TOEFL_2.json',
    length: 9213,
    category: '国际考试',
    tags: ['所有', 'TOEFL'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word,
  },
  {
    id: 'GRE_2',
    name: 'GRE 词汇',
    description: 'GRE 词汇',
    url: 'GRE_2.json',
    length: 7199,
    category: '国际考试',
    tags: ['所有', 'GRE'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word,
  },
  {
    id: 'SAT_2',
    name: 'SAT 词汇',
    description: 'SAT 词汇',
    url: 'SAT_2.json',
    length: 4423,
    category: '国际考试',
    tags: ['所有', 'SAT'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word,
  },
  {
    id: 'GMAT_2',
    name: 'GMAT 词汇',
    description: 'GMAT 词汇',
    url: 'GMAT_2.json',
    length: 3254,
    category: '国际考试',
    tags: ['所有', 'GMAT'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word,
  },
  {
    id: 'IELTS_3',
    name: '新东方雅思词汇',
    description: '新东方雅思词汇',
    url: 'IELTS_3.json',
    length: 3575,
    category: '国际考试',
    tags: ['所有', 'IELTS', '新东方'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word,
  },
  {
    id: 'TOEFL_3',
    name: '新东方 TOEFL 词汇',
    description: '新东方 TOEFL 词汇',
    url: 'TOEFL_3.json',
    length: 4264,
    category: '国际考试',
    tags: ['所有', 'TOEFL', '新东方'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word,
  },
  {
    id: 'GRE_3',
    name: '新东方 GRE 词汇',
    description: '新东方 GRE 词汇',
    url: 'GRE_3.json',
    length: 6515,
    category: '国际考试',
    tags: ['所有', '新东方', 'GRE'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word,
  },
  {
    id: 'SAT_3',
    name: '新东方 SAT 词汇',
    description: '新东方 SAT 词汇',
    url: 'SAT_3.json',
    length: 4464,
    category: '国际考试',
    tags: ['所有', '新东方', 'SAT'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word,
  },
  {
    id: 'GMAT_3',
    name: '新东方 GMAT 词汇',
    description: '新东方 GMAT 词汇',
    url: 'GMAT_3.json',
    length: 3047,
    category: '国际考试',
    tags: ['所有', '新东方', 'GMAT'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word,
  },

  {
    id: 'IELTS_2',
    name: '雅思词汇',
    description: '雅思词汇',
    url: 'IELTS_2.json',
    length: 3427,
    category: '国际考试',
    tags: ['所有', 'IELTS'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word,
  },
]

// 中国考试
const chinaExam: DictResource[] = [
  {
    id: 'CET4_1',
    name: '四级真题核心词',
    description: '四级真题核心词',
    url: 'CET4_1.json',
    length: 1162,
    category: '中国考试',
    tags: ['所有', '大学英语', '四级',],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word
  },
  {
    id: 'CET6_1',
    name: '六级真题核心词',
    description: '六级真题核心词',
    url: 'CET6_1.json',
    length: 1228,
    category: '中国考试',
    tags: ['所有', '大学英语', '六级'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word
  },
  {
    id: 'Level4_1',
    name: '专四真题高频词',
    description: '专四真题高频词',
    url: 'Level4_1.json',
    length: 595,
    category: '中国考试',
    tags: ['所有', '大学英语'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word
  },
  {
    id: 'Level8_1',
    name: '专八真题高频词',
    description: '专八真题高频词',
    url: 'Level8_1.json',
    length: 684,
    category: '中国考试',
    tags: ['所有', '大学英语'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word
  },
  {
    id: 'CET4_2',
    name: '四级英语词汇',
    description: '四级英语词汇',
    url: 'CET4_2.json',
    length: 3739,
    category: '中国考试',
    tags: ['所有', '大学英语', '四级'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word
  },
  {
    id: 'CET6_2',
    name: '六级英语词汇',
    description: '六级英语词汇',
    url: 'CET6_2.json',
    length: 2078,
    category: '中国考试',
    tags: ['所有', '大学英语', '六级'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word
  },
  {
    id: 'Level4_2',
    name: '专四核心词汇',
    description: '专四核心词汇',
    url: 'Level4_2.json',
    length: 4025,
    category: '中国考试',
    tags: ['所有', '大学英语'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word,
  },
  {
    id: 'Level8_2',
    name: '专八核心词汇',
    description: '专八核心词汇',
    url: 'Level8_2.json',
    length: 12197,
    category: '中国考试',
    tags: ['所有', '大学英语'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word,
  },
  {
    id: 'CET4_3',
    name: '新东方四级词汇',
    url: 'CET4_3.json',
    length: 2607,
    category: '中国考试',
    tags: ['所有', '大学英语', '四级', '新东方'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word,
    description: ''
  },
  {
    id: 'CET6_3',
    name: '新东方六级词汇',
    description: '新东方六级词汇',
    url: 'CET6_3.json',
    length: 2345,
    category: '中国考试',
    tags: ['所有', '大学英语', '六级', '新东方'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word,
  },
  {
    id: 'KaoYan_2',
    name: '考研英语词汇',
    description: '考研英语词汇',
    url: 'KaoYan_2.json',
    length: 4533,
    category: '中国考试',
    tags: ['所有', '考研'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word,
  },
  {
    id: 'KaoYan_1',
    name: '考研必考词汇',
    description: '考研必考词汇',
    url: 'KaoYan_1.json',
    length: 1341,
    category: '中国考试',
    tags: ['所有', '考研'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word
  },
  {
    id: 'KaoYan_3',
    name: '新东方考研词汇',
    description: '新东方考研词汇',
    url: 'KaoYan_3.json',
    length: 3728,
    category: '中国考试',
    tags: ['所有', '考研', '新东方'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word,
  },
]

// 青少儿英语
const childrenEnglish: DictResource[] =[
  {
    id: 'ChuZhong_2',
    name: '初中英语词汇',
    description: '初中英语词汇',
    url: 'ChuZhong_2.json',
    length: 1420,
    category: '青少年英语',
    tags: ['所有', '通用', '初中'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word,
  },
  {
    id: 'GaoZhong_2',
    name: '高中英语词汇',
    description: '高中英语词汇',
    url: 'GaoZhong_2.json',
    length: 3668,
    category: '青少年英语',
    tags: ['所有', '通用', '高中'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word,
  },
  {
    id: 'ChuZhong_3',
    name: '新东方初中词汇',
    description: '新东方初中词汇',
    url: 'ChuZhong_3.json',
    length: 1803,
    category: '青少年英语',
    tags: ['所有', '通用', '初中'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word,
  },
  {
    id: 'GaoZhong_3',
    name: '新东方高中词汇',
    description: '新东方高中词汇',
    url: 'GaoZhong_3.json',
    length: 2340,
    category: '青少年英语',
    tags: ['所有', '通用', '高中'],
    translateLanguage: 'common',
    language: 'en',
    type: DictType.word,
  },
]

export const newDicts = [
  ...internationalExam,
  ...chinaExam,
  ...childrenEnglish,
]
