<script setup lang="ts">

import Toolbar from "@/components/Toolbar/Toolbar.vue"
import {onMounted, watch} from "vue";
import {usePracticeStore} from "@/components/Practice/usePracticeStore.ts";
import Footer from "@/components/Practice/Footer.vue";
import TypeWord from "@/components/Practice/TypeWord.vue";
import TypeArticle from "@/components/Practice/TypeArticle.vue";
import {useBaseStore} from "@/stores/base.ts";
import {$ref} from "vue/macros";
import Statistics from "@/components/Practice/Statistics.vue";

const practiceStore = usePracticeStore()
const store = useBaseStore()

watch(practiceStore, () => {
  if (practiceStore.inputNumber < 1) {
    return practiceStore.correctRate = -1
  }
  if (practiceStore.wrongNumber > practiceStore.inputNumber) {
    return practiceStore.correctRate = 0
  }
  practiceStore.correctRate = 100 - Math.trunc(((practiceStore.wrongNumber) / (practiceStore.inputNumber)) * 100)
})

let wordData = $ref({
  words: [],
  index: -1
})

let articleData = $ref({
  article: {
    "title": "A private conversation!",
    "titleTranslate": "私人谈话！",
    "article": "Last week I went to the theatre. I had a very good seat. The play was very interesting. I did not enjoy it. A young man and a young woman were sitting behind me. They were talking loudly. I got very angry. I could not hear the actors. I turned round. I looked at the man and the woman angrily. They did not pay any attention. In the end, I could not bear it. I turned round again. ‘I can't hear a word!’ I said angrily.\n‘It's none of your business, ’ the young man said rudely. ‘This is a private conversation!’",
    "customTranslate": "",
    "networkTranslate": "上周我去了剧院。\n我坐得很好。\n这出戏很有趣。\n我不喜欢它。\n一个年轻男子和一个年轻女子坐在我身后。\n他们大声说话。\n我很生气。\n我听不见演员们的声音。\n我转过身来。\n我愤怒地看着那个男人和那个女人。\n他们没有理会。\n最后\n我无法忍受。\n我又转过身来。\n“我一个字也听不见！”\n我生气地说。\n\n“这不关你的事，”\n那个年轻人粗鲁地说。\n“这是私人谈话！”\n\n",
    "newWords": [],
    "articleAllWords": [],
    "sections": [
      [{
        "text": "Last week I went to the theatre. ",
        "translate": "上周我去了剧院。",
        "words": [{
          "name": "Last",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "week",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "I",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "went",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "to",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "the",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "theatre",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": ".",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": true,
          "symbolPosition": ""
        }]
      }, {
        "text": "I had a very good seat. ",
        "translate": "我坐得很好。",
        "words": [{
          "name": "I",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "had",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "a",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "very",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "good",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "seat",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": ".",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": true,
          "symbolPosition": ""
        }]
      }, {
        "text": "The play was very interesting. ",
        "translate": "这出戏很有趣。",
        "words": [{
          "name": "The",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "play",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "was",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "very",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "interesting",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": ".",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": true,
          "symbolPosition": ""
        }]
      }, {
        "text": "I did not enjoy it. ",
        "translate": "我不喜欢它。",
        "words": [{
          "name": "I",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "did",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "not",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "enjoy",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "it",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": ".",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": true,
          "symbolPosition": ""
        }]
      }, {
        "text": "A young man and a young woman were sitting behind me. ",
        "translate": "一个年轻男子和一个年轻女子坐在我身后。",
        "words": [{
          "name": "A",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "young",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "man",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "and",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "a",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "young",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "woman",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "were",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "sitting",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "behind",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "me",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": ".",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": true,
          "symbolPosition": ""
        }]
      }, {
        "text": "They were talking loudly. ",
        "translate": "他们大声说话。",
        "words": [{
          "name": "They",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "were",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "talking",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "loudly",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": ".",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": true,
          "symbolPosition": ""
        }]
      }, {
        "text": "I got very angry. ",
        "translate": "我很生气。",
        "words": [{
          "name": "I",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "got",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "very",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "angry",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": ".",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": true,
          "symbolPosition": ""
        }]
      }, {
        "text": "I could not hear the actors. ",
        "translate": "我听不见演员们的声音。",
        "words": [{
          "name": "I",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "could",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "not",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "hear",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "the",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "actors",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": ".",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": true,
          "symbolPosition": ""
        }]
      }, {
        "text": "I turned round. ",
        "translate": "我转过身来。",
        "words": [{
          "name": "I",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "turned",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "round",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": ".",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": true,
          "symbolPosition": ""
        }]
      }, {
        "text": "I looked at the man and the woman angrily. ",
        "translate": "我愤怒地看着那个男人和那个女人。",
        "words": [{
          "name": "I",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "looked",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "at",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "the",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "man",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "and",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "the",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "woman",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "angrily",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": ".",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": true,
          "symbolPosition": ""
        }]
      }, {
        "text": "They did not pay any attention. ",
        "translate": "他们没有理会。",
        "words": [{
          "name": "They",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "did",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "not",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "pay",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "any",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "attention",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": ".",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": true,
          "symbolPosition": ""
        }]
      }, {
        "text": "In the end, ",
        "translate": "最后",
        "words": [{
          "name": "In",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "the",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "end",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": ",",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": true,
          "symbolPosition": ""
        }]
      }, {
        "text": "I could not bear it. ",
        "translate": "我无法忍受。",
        "words": [{
          "name": "I",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "could",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "not",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "bear",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "it",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": ".",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": true,
          "symbolPosition": ""
        }]
      }, {
        "text": "I turned round again. ",
        "translate": "我又转过身来。",
        "words": [{
          "name": "I",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "turned",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "round",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "again",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": ".",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": true,
          "symbolPosition": ""
        }]
      }, {
        "text": "\"I can't hear a word!\" ",
        "translate": "“我一个字也听不见！”",
        "words": [{
          "name": "\"",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": true,
          "symbolPosition": "start"
        }, {
          "name": "I",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "can't",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "hear",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "a",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "word",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "!",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": true,
          "symbolPosition": ""
        }, {
          "name": "\"",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": true,
          "symbolPosition": "end"
        }]
      }, {
        "text": "I said angrily. ",
        "translate": "我生气地说。",
        "words": [{
          "name": "I",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "said",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "angrily",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": ".",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": true,
          "symbolPosition": ""
        }]
      }], [{
        "text": "\"It's none of your business,\" ",
        "translate": "“这不关你的事，”",
        "words": [{
          "name": "\"",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": true,
          "symbolPosition": "start"
        }, {
          "name": "It's",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "none",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "of",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "your",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "business",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": ",",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": true,
          "symbolPosition": ""
        }, {
          "name": "\"",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": true,
          "symbolPosition": "end"
        }]
      }, {
        "text": "the young man said rudely. ",
        "translate": "那个年轻人粗鲁地说。",
        "words": [{
          "name": "the",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "young",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "man",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "said",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "rudely",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": ".",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": true,
          "symbolPosition": ""
        }]
      }, {
        "text": "\"This is a private conversation!\" ",
        "translate": "“这是私人谈话！”",
        "words": [{
          "name": "\"",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": true,
          "symbolPosition": "start"
        }, {
          "name": "This",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "is",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "a",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "private",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "conversation",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": false,
          "symbolPosition": ""
        }, {
          "name": "!",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": false,
          "isSymbol": true,
          "symbolPosition": ""
        }, {
          "name": "\"",
          "usphone": "",
          "ukphone": "",
          "trans": [],
          "nextSpace": true,
          "isSymbol": true,
          "symbolPosition": "end"
        }]
      }]
    ],
    "isTranslated": false,
    "translateType": 0
  },
  sectionIndex: 0,
  sentenceIndex: 0,
  wordIndex: 0,
  stringIndex: 0,
})

watch(() => store.load, n => {
  if (n) {
    wordData.words = store.chapter
    wordData.index = 0
  }
})

onMounted(() => {

})

</script>

<template>
  <div class="practice">
    <Toolbar/>
    <TypeArticle
        v-if="practiceStore.type === 'article'"
        :article="articleData.article"
        :sectionIndex="articleData.sectionIndex"
        :sentenceIndex="articleData.sentenceIndex"
        :wordIndex="articleData.wordIndex"
        :stringIndex="articleData.stringIndex"
    />
    <TypeWord
        :words="wordData.words"
        :index="wordData.index"
        v-else/>
    <Footer/>
  </div>
  <Statistics/>
</template>

<style scoped lang="scss">
.practice {
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}
</style>